name: Update Terraform Cloud Workspace
description: Updates a Terraform Cloud workspace settings
inputs:
  tfcToken:
    description: A Terraform Cloud API token with access to manage workspaces
    required: true

  orgName:
    description: The name of the Terraform Cloud organization in which to create the workspace
    required: true

  workspaceName:
    description: The name of the Terraform Cloud workspace
    required: true

  setDescription:
    description: Set the workspace description
    required: false

  setVCSIdentifier:
    description: Set the VCS repo to connect, e.g. some-org/some-repo
    required: false

  setVCSBranch:
    description: Set the VCS repo branch to connect
    required: false

  setVCSOAuthTokenID:
    description: Set the OAuth token ID used to authorize the connection
    required: false

  setWorkingDirectory:
    description: Set the directory that Terraform will execute within
    required: false

  setApplyMethod:
    description: |
      The workspace apply method. Allowed values: auto, manual
    required: false

  unsetDescription:
    description: Unset the workspace description
    required: false
    default: false

  unsetVCSIdentifier:
    description: Unset the VCS repo to connect, e.g. some-org/some-repo
    required: false
    default: false

  unsetVCSBranch:
    description: Unset the VCS repo branch to connect
    required: false
    default: false

  unsetVCSOAuthTokenID:
    description: Unset the OAuth token ID used to authorize the connection
    required: false
    default: false

  unsetWorkingDirectory:
    description: Unset the directory that Terraform will execute within
    required: false
    default: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: arrow-up-right
  color: blue
