name: Update TFC Workspace
description: Updates a Terraform Cloud workspace settings
inputs:
  tfcToken:
    description: A Terraform Cloud API token with access to manage workspaces
    required: true
  orgName:
    description: The name of the Terraform Cloud organization in which to create the workspace
    required: true
  workspaceName:
    description: The name of the Terraform Cloud workspace
    required: true
  description:
    description: The workspace description
    required: true
  vcsIdentifier:
    description: The VCS repo to connect, e.g. some-org/some-repo
    required: true
  vcsBranch:
    description: The VCS repo branch to connect
    required: true
  vcsOAuthTokenID:
    description: The OAuth token ID used to authorize the connection
    required: true
  workingDirectory:
    description: The directory that Terraform will execute within
    required: true

runs:
  using: docker
  image: docker://frostedcarbon/tfc-cli:v0.10.0
  args:
    - workspaces
    - update
    - -token
    - ${{ inputs.tfcToken }}
    - -org
    - ${{ inputs.orgName }}
    - -workspace
    - ${{ inputs.workspaceName }}
    - -description
    - ${{ inputs.description }}
    - -vcs-identifier
    - ${{ inputs.vcsIdentifier }}
    - -vcs-branch
    - ${{ inputs.vcsBranch }}
    - -vcs-oauth-token-id
    - ${{ inputs.vcsOAuthTokenID }}
    - -working-directory
    - ${{ inputs.workingDirectory }}

branding:
  icon: arrow-up-right
  color: blue
